### ISSUE TITLE
Wrong behavior method executed

### ISSUE THREAD

**Issue by zetas** [UnionOfRAD/li3_behaviors#1]
So I have 2 behaviors on a model, each one has it's own methods that are unique to it, but both share a single common method name that basically does the same thing but slightly differently depending on the behavior. For some reason though, when executing this method on the second listed behavior, the code tries to execute the method on the first behavior instead. 

I've gone over the code, time and time again, the behavior is set only once, at the top of the page, and it's set properly. The two matching methods do have different signatures though, im not sure if that is why it's happening.

I'm using lithium 1.1 with li3_behaviors 2.0.

Here's the offending code (only included relevant parts):

```php
class Donation extends Model
{
    use Behaviors;

    protected $_actsAs = [
        'StripeDonation' => ['devMode' => false],
        'BtcDonation' => ['fields' => ['btc_received_value', 'btc_required_value']]
    ];

}

class StripeDonation extends Behavior
{
    protected static $_defaults = ['devMode' => false];

    public function completePayment($model, $behavior, $entity, $token, $email) {}
}

class BtcDonation extends Behavior
{
   protected static $_defaults = ['fields' => ['btc_received_value', 'btc_required_value']];

   public function completePayment($model, $behavior, $entity, $secret) {}
}

#Implementation

use app\models\Donation;

Donation::bindBehavior('BtcDonation');

$donation = Donation::find(3);
$donation->completePayment('thesecret');

#Error received: Missing argument 5 for  
#app\extensions\data\behavior\StripeDonation::completePayment(), called in
# /data/base/libraries/lithium/core/Object.php on line 146 and defined
```

**Comment by mariuswilms** [comment]
In this case is the method call routed to the last behavior bound to the model. That is expected behavior. It seems there might be a misunderstanding: what did you expect to see?

**Comment by zetas** [comment]
Hmm, I thought since I bound the BtcDonation behavior it would execute the completePayment method on that behavior, not the StripeDonation behavior. If you look at the implementation code at the bottom of my example you can see that StripeDonation is not bound, nor is it used anywhere in the execution.

**Comment by mariuswilms** [comment]
Simply by specifying a behavior in the actsAs property the behavior is bound (automatically). bind()/unbind() is for runtime manipulation only. Hope that explains it.

**Comment by zetas** [comment]
Ok, so instead of specifying the bind in the runtime as I have been doing, I have to instead unbind the behavior I don't want. Ok. Thats a bit weird but I understand.

**Comment by mariuswilms** [comment]
...or just use bind/unbind and actsAs not at all.

**Comment by zetas** [comment]
Ok thanks. The lack of examples makes this kinda tricky to understand so I
appreciate your guidance.

On Jul 21, 2017, at 5:29 PM, David Persson <notifications@github.com> wrote:

...or just use bind/unbind and actsAs not at all.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UnionOfRAD/li3_behaviors/issues/1#issuecomment-317116985>,
or mute the thread
